### ISSUE TITLE
Cant run app

### ISSUE THREAD

**Issue by angryahmed** [CodeSprut/GiftSeeker#16]
I have popup with message - 'No translations found on storage' and nothing happen. I used giftseeker some time ago but now I can't run it :(

**Comment by WandaIstWeg** [comment]
![image](https://user-images.githubusercontent.com/35782554/141931993-d36f7ac0-ef94-4663-82a2-f49a31f595be.png)

**Comment by angryahmed** [comment]
Why closed, still not working/ no solution ?

**Comment by codesprut** [comment]
> Why closed, still not working/ no solution ?

Hello!

Solution is here https://github.com/CodeSprut/GiftSeeker/releases/tag/2.24
