### ISSUE TITLE
не собирается под линукс

### ISSUE THREAD

**Issue by nikrovir** [CodeSprut/GiftSeeker#18]
выбрасывает сборку билда с ошибками:
unknown output format set
github.com/develar/app-builder/pkg/icons.convertSingleFile
	/Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:305
github.com/develar/app-builder/pkg/icons.doConvertIcon
	/Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:247
github.com/develar/app-builder/pkg/icons.ConvertIcon
	/Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:56
github.com/develar/app-builder/pkg/icons.ConfigureCommand.func1
	/Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:33
github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
	/Volumes/data/Documents/app-builder/main.go:90
runtime.main
	/usr/local/Cellar/go/1.16.5/libexec/src/runtime/proc.go:225
runtime.goexit
	/usr/local/Cellar/go/1.16.5/libexec/src/runtime/asm_amd64.s:1371

**Comment by codesprut** [comment]
Багу фиксанул, но похоже под линуксом есть ещё косяк. Для приложения не создаётся директория и прога может не стартовать.

С этой проблемой разобрался в другой ветке, где делаю консольный интерфейс без electron.

Пока предлагаю временное решение:
До первого запуска в домашней директории юзера нужно создать директорию GiftSeeker.
