### ISSUE TITLE
Language not english

### ISSUE THREAD

**Issue by vaibhavpacharya** [CodeSprut/GiftSeeker#2]
![Screenshot (53)](https://user-images.githubusercontent.com/16417441/87255472-e314db00-c43f-11ea-824b-aca5f20ec130.png)

Can you please update the language to English. Its really very hard to understand.

**Comment by codesprut** [comment]
Hello. Program have english but not as default. Please open second menu item and use first selectbox.
I will switch to english default in next update.

13.07.2020, 01:02, "Vaibhav Acharya" <notifications@github.com>:
Can you please update the language to English. Its really very hard to understand.
