### ISSUE TITLE
GiftSeeker занимается обработкой графики?

### ISSUE THREAD

**Issue by alfacom** [CodeSprut/GiftSeeker#7]
Привет!
В папке с прогой независимо от системы находятся библиотеки для работы с 3д графикой и видео - libEGL, libGLESv2, d3dcompiler_47, swiftshader, vulkan, ffmpeg.
Но ведь GiftSeeker не занимается обработкой графики. Можешь подсказать, зачем они нужны?
Меня смущает, что при запуске GS требует доступа к ним и валится при отказе:
![image](https://user-images.githubusercontent.com/1672524/103088368-a6a6f700-45fb-11eb-911e-9da7654f8390.png)

**Comment by codesprut** [comment]
Привет.
Всё, что делает программа можно увидеть в коде - обработка графики в её функционал не входит, однако не исключаю, что они нужны для корректной работы браузера.

Нужно поресёрчить, почему электрон держит в себе эти файлы и могу ли я их исключить при сборке без каких либо последствий - подробного понимания как работает браузер у меня пока нет, а GS это ни что иное как chromium(electron).

Если вы уже обладаете подобными знаниями, то буду признателен за подсказку.
